// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview Summarizes the content of an SEC filing using AI.
 *
 * - summarizeSecFiling - A function that summarizes the SEC filing content.
 * - SummarizeSecFilingInput - The input type for the summarizeSecFiling function.
 * - SummarizeSecFilingOutput - The return type for the summarizeSecFiling function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';
import {getSecFilingContent} from '@/services/sec-scraper';

const SummarizeSecFilingInputSchema = z.object({
  url: z.string().describe('The URL of the SEC filing.'),
});
export type SummarizeSecFilingInput = z.infer<typeof SummarizeSecFilingInputSchema>;

const SummarizeSecFilingOutputSchema = z.object({
  summary: z.string().describe('The summarized content of the SEC filing.'),
});
export type SummarizeSecFilingOutput = z.infer<typeof SummarizeSecFilingOutputSchema>;

export async function summarizeSecFiling(input: SummarizeSecFilingInput): Promise<SummarizeSecFilingOutput> {
  return summarizeSecFilingFlow(input);
}

const summarizeSecFilingPrompt = ai.definePrompt({
  name: 'summarizeSecFilingPrompt',
  input: {
    schema: z.object({
      secFilingContent: z.string().describe('The content of the SEC filing.'),
    }),
  },
  output: {
    schema: z.object({
      summary: z.string().describe('The summarized content of the SEC filing.'),
    }),
  },
  prompt: `Summarize the following SEC filing content:\n\n{{{secFilingContent}}}`,
});

const summarizeSecFilingFlow = ai.defineFlow<
  typeof SummarizeSecFilingInputSchema,
  typeof SummarizeSecFilingOutputSchema
>(
  {
    name: 'summarizeSecFilingFlow',
    inputSchema: SummarizeSecFilingInputSchema,
    outputSchema: SummarizeSecFilingOutputSchema,
  },
  async input => {
    const secFiling = await getSecFilingContent(input.url);
    const {output} = await summarizeSecFilingPrompt({
      secFilingContent: secFiling.textContent,
    });
    return output!;
  }
);
