it r// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview Summarizes the content of an SEC filing using AI.
 *
 * - summarizeSecFiling - A function that summarizes the SEC filing content.
 * - SummarizeSecFilingInput - The input type for the summarizeSecFiling function.
 * - SummarizeSecFilingOutput - The return type for the summarizeSecFiling function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';
import {getSecFilingContent} from '@/services/sec-scraper';
import {AI_CONFIG} from '@/config/ai';

const SummarizeSecFilingInputSchema = z.object({
  url: z.string().describe('The URL of the SEC filing.'),
});
export type SummarizeSecFilingInput = z.infer<typeof SummarizeSecFilingInputSchema>;

// Revert OutputSchema to the object structure
const SummarizeSecFilingOutputSchema = z.object({
  summary: z.string().describe('The summarized content of the SEC filing.'),
});
export type SummarizeSecFilingOutput = z.infer<typeof SummarizeSecFilingOutputSchema>;

export async function summarizeSecFiling(input: SummarizeSecFilingInput): Promise<SummarizeSecFilingOutput> {
  return summarizeSecFilingFlow(input);
}

// Bring back the inline ai.definePrompt block
const summarizeSecFilingPrompt = ai.definePrompt({
  name: 'summarizeSecFilingPrompt',
  input: {
    schema: z.object({
      secFilingContent: z.string().describe('The content of the SEC filing.'),
    }),
  },
  output: {
    schema: SummarizeSecFilingOutputSchema, // Use the object schema for output
  },
  // Add generation config here
  config: AI_CONFIG.generationConfig,
  prompt: `Summarize the following SEC filing content in 3 paragraphs.
  
  Paragraph 1 - Focuses on Earning Performance
  Paragraph 2 = Focuses on Cash flow and Balance sheet
  Paragraph 3 - Focuses on Forward Guidances and macro commentaries:

{{{secFilingContent}}}`,
});

const summarizeSecFilingFlow = ai.defineFlow<
  typeof SummarizeSecFilingInputSchema,
  typeof SummarizeSecFilingOutputSchema // Use the object schema
>(
  {
    name: 'summarizeSecFilingFlow',
    inputSchema: SummarizeSecFilingInputSchema,
    outputSchema: SummarizeSecFilingOutputSchema, // Flow output is object
  },
  async input => {
    const secFiling = await getSecFilingContent(input.url);
    // Call the defined prompt function
    const {output} = await summarizeSecFilingPrompt({
      secFilingContent: secFiling.textContent,
    });
    return output!;
  }
);
